<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
//"swatchRenderer": {
?>
<?php /** @var $block \Magento\Swatches\Block\Product\Renderer\Configurable */ ?>
<?php /** @var $escaper \Magento\Framework\Escaper */ ?>
<div class="swatch-opt" data-role="swatch-options"></div>

<script type="text/x-magento-init">
    {
        "[data-role=swatch-options]": {
            "Magento_Swatches/js/swatch-renderer": {
                "baseUrl": "<?= $block->getBaseUrl() ?>",
                "jsonConfig": null,
                "jsonSwatchConfig": "<?= $block->getJsonSwatchConfig() ?>",
                "mediaCallback": "<?= /* @escapeNotVerified */ $block->getMediaCallback() ?>",
                "gallerySwitchStrategy": "<?= $block->getVar('gallery_switch_strategy','Magento_ConfigurableProduct') ?: 'replace' ?>",
                "jsonSwatchImageSizeConfig": "<?= $block->getJsonSwatchSizeConfig() ?: 'null' ?>"
            },
            "Magento_Swatches/js/configurable-customer-data": {
                    "swatchOptions": null
            }
        }
    }
</script>
